#' Rename taxa in a phyloseq object using a fasta key
#'
#' @param physeq A phyloseq object whose taxa_names are long ASV sequences.
#' @param fasta_df A data frame with two columns: "seq.name" containing human-readable
#' identifiers (e.g., "seq1", "seq2") and "seq.text" containing the corresponding ASV sequences.
#' This can be generated by reading in a fasta file using tools like phylotools' read.fasta function.
#'
#' @return Returns a phyloseq object where the taxa names (ASV sequences) are replaced with the
#' corresponding short names from the fasta key.
#' If any sequences in the phyloseq object are not found in the key, they will be left unchanged
#' and a warning will be issued.
#'
#' @export
#'
rename_taxa_with_short_names <- function(physeq, fasta_df) {
  # Ensure input is a phyloseq object
  if (!inherits(physeq, "phyloseq")) {
    stop("physeq must be a phyloseq object")
  }

  # Ensure fasta_df has the required columns
  if (!all(c("seq.name", "seq.text") %in% colnames(fasta_df))) {
    stop("fasta_df must contain columns 'seq.name' and 'seq.text'")
  }

  # Get current taxa names from phyloseq object
  current_taxa = phyloseq::taxa_names(phyloseq::otu_table(physeq))

  # Create named vector: names are full sequences, values are short names
  seq_map = stats::setNames(fasta_df$seq.name, fasta_df$seq.text)

  # Check that all taxa in phyloseq are present in the fasta table
  if (!all(current_taxa %in% names(seq_map))) {
    missing <- setdiff(current_taxa, names(seq_map))
    warning("Some taxa in the phyloseq object are not present in the fasta mapping and will be left unchanged.")
  }

  # Replace taxa names using the mapping
  new_taxa <- unname(seq_map[current_taxa])
  phyloseq::taxa_names(physeq) <- new_taxa

  return(physeq)
}
